-- Creating USERS table
CREATE TABLE USERS (
   USER_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
   USERNAME VARCHAR(50),
   FIRST_NAME VARCHAR(50),
   LAST_NAME VARCHAR(50),
   EMAIL VARCHAR(50),
   PASSWORD INTEGER,
   BALANCE DOUBLE
);

-- Creating FOODS table
CREATE TABLE FOODS (
   FOOD_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
   FOOD_NAME VARCHAR(50),
   FOOD_PRICE DOUBLE,
   INGREDIENTS VARCHAR(255)
);

-- Creating USER_HAS_FOOD table
CREATE TABLE USER_HAS_FOOD (
   USER_ID INT,
   FOOD_ID INT,
   FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
   FOREIGN KEY (FOOD_ID) REFERENCES FOODS (FOOD_ID),
   CONSTRAINT PK_USER_ITEM PRIMARY KEY (USER_ID, FOOD_ID)
);

-- Populating the tables
--   Adding USERS
INSERT INTO USERS (USERNAME, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, BALANCE) VALUES ('lisa', 'lisa', 'simpson', 'lisa@simpson.com', 1509442, 0.0);
INSERT INTO USERS (USERNAME, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, BALANCE) VALUES ('marge', 'marge', 'simpson', 'marge@simpson.com', 1509442, 0.0);
INSERT INTO USERS (USERNAME, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, BALANCE) VALUES ('bart', 'bart', 'simpson', 'bart@simpson.com', 1509442, 0.0);
--   Adding foods to FOODS
INSERT INTO FOODS (FOOD_NAME, FOOD_PRICE, INGREDIENTS) VALUES ('Pasta', 15.0, 'spaghetti, pesto sauce, parmigiano');
INSERT INTO FOODS (FOOD_NAME, FOOD_PRICE, INGREDIENTS) VALUES ('Pizza', 12.0,  'dough, tomato sauce, mozarella');
INSERT INTO FOODS (FOOD_NAME, FOOD_PRICE, INGREDIENTS) VALUES ('Chicken Curry', 18.0, 'chicken, curry sauce');